basic_scaling:
  max_instances: 1
  idle_timeout: 5m
# manual_scaling:
#   instances: 2
# includes:
#   - .env.yaml
instance_class: B1
runtime: nodejs12
entrypoint: node ./build/src/index.js
# network:
#   session_affinity: true
