basic_scaling:
  max_instances: 1
  idle_timeout: 5m
entrypoint: node ./build/src/index.js
env_variables:
  FRONTEND_DOMAIN: https://project-id-shortlink.web.app/
instance_class: B1
runtime: nodejs12
