#!/usr/bin/env bash

GIT_DIR=$(git rev-parse --show-toplevel)
cd ${GIT_DIR}
trap "cd ${GIT_DIR}" err exit

case $1 in
frontend)
    cd frontend
    npm run dev -- --open
    ;;
backend)
    cd backend
    npm run dev
    ;;
*)
    echo 'Invalid dev target {frontend|backend}'
    exit -1
    ;;
esac
