#!/usr/bin/env bash

GIT_DIR=$(git rev-parse --show-toplevel)
cd ${GIT_DIR}
trap "cd ${GIT_DIR}" err exit

case $1 in
app)
    cd app
    npm run dev
    ;;
server)
    cd server
    npm run dev
    ;;
*)
    echo 'Invalid dev target {app|server}'
    exit -1
    ;;
esac
