#!/usr/bin/env bash

GIT_DIR=$(git rev-parse --show-toplevel)
cd ${GIT_DIR}
trap "cd ${GIT_DIR}" err exit

OUT_DIR=${1:-./}

# generate javascript
./backend/node_modules/.bin/pbjs -t static-module -o ${OUT_DIR}/gen.js proto/*
# add typescript types
./backend/node_modules/.bin/pbts -o ${OUT_DIR}/gen.d.ts ${OUT_DIR}/gen.js
